### ISSUE TITLE
[Feature request] Do the cert generation optional

### ISSUE THREAD

**Issue by dgdavid** [tx44/cloudlog-docker#3]
@tx44 

Thanks a lot for your amazing work here. It works pretty good!

Just wondering if I can suggest making the certification generation optional, via variable in .env file, by asking to the user in the `install` script or whatever other way you considered better.

Thanks!

**Comment by m0spf** [comment]
Hi @dgdavid glad it is working ok for you. I have been meaning to come back to this project to make some improvements and have just added a few issues that need sorting.

My intention for SSL was that if the instance is public facing then letsencrypt automatically takes care of cert issue/renewal, however if the instance is private then a self signed cert is generated. I dont suppose it would be any harm having an option to disable SSL entirely, however this isnt really best practice even if the instance is local.

Is there a particular reason you want to disable certs, did you have issues with the automation generation?

**Comment by dgdavid** [comment]
Sorry, I don't know too much about SSL/certs generation. Just thinking in services that already cares about it. Maybe incompatible with this kind of automation?

Thanks a lot for the explanation. Much appreciated.

**Comment by dgdavid** [comment]
> Just thinking in services that already cares about it.

And to avoid the browser warning in a _development mode_ (see #5)

**Comment by dgdavid** [comment]
As said in https://github.com/m0spf/cloudlog-docker/issues/5#issuecomment-910256269

> Closing it because I quit using Cloudlog. For sure, anyone else interested on it can reopen the issue.
