### ISSUE TITLE
[Question] Why doing replacements one by one

### ISSUE THREAD

**Issue by dgdavid** [tx44/cloudlog-docker#4]
Just out of curiosity, I would like to know why you are running a new container for each replacement in the config files

https://github.com/tx44/cloudlog-docker/blob/e2ea95fc371320c9b0dbf4ee5d17a33e7f5f29e4/install.sh#L66-L88

instead of performing all of them in the same container.

Also wondering why you did not _extract_ that logic to another script called during the install one.

Thanks a lot in advance.

**Comment by m0spf** [comment]
Sorry for the delayed reply, you are right, most of these commands could be executed in a single container, i'll add this to my list, or feel free to submit a PR.

**Comment by dgdavid** [comment]
> or feel free to submit a PR.

I thought to do it, but finally I stop using Cloudlog. I really sorry not being not much helping here.
