### ISSUE TITLE
[Feature request] Add support for development mode

### ISSUE THREAD

**Issue by dgdavid** [tx44/cloudlog-docker#5]
Hi,

As far as I can see, this is a production-ready Cloudlog dockerization. And, as I said, it works pretty well.

That said, I wonder if it would be possible to add support for a development mode, using a local copy/repo of Cloudlog instead of cloning the latest version from upstream.

My first dirty attempt was to try a symlink to test the idea

```diff
echo ""
echo "*** Creating directories and cloning cloudlog repo from git"
echo ""
- mkdir -p $DIR/data/cloudlog
mkdir -p $DIR/data/backup/auto
- git clone https://github.com/magicbug/Cloudlog.git $DIR/data/cloudlog/
+ ln -sT /path/to/local/Cloudlog/copy $DIR/data/cloudlog/
```

but, of course, it didn't work :)

```
*** Creating config.php and database.php configs

sed: can't read /data/cloudlog/application/config/config.php: No such file or directory
sed: can't read /data/cloudlog/application/config/config.php: No such file or directory
...
```

What do you think @tx44? Does adding support for a development mode make sense? Would it worth? Or is it too much work?

Thanks!

**Comment by m0spf** [comment]
Hi @dgdavid, when I am doing development I tend to just have a copy of the code in a separate folder and I change the .env file APP_NAME, that way the entire stack is separate from production. Would doing something like that work for you or have I misunderstood?

**Comment by dgdavid** [comment]
Hi @tx44, 

Thanks a lot for the answer. Sadly, I do not get the concept. How can it work just changing the APP_NAME? Could yo put an example?

To clarify what I mean, the context is to tell the script where I have my local copy (where I could have been working before running the script for the first time).

Thanks!

**Comment by dgdavid** [comment]
Closing it because I quit using Cloudlog. For sure, anyone else interested on it can reopen the issue.

Thanks!
